Snyk Code / Test / IAC scan will pass if valid files are not found.
fabasoad/pre-commit-snyk pull request #44
Opened 2024-04-03 11:19 UTC by Kieharper

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] I have read the [CONTRIBUTING](https://github.com/fabasoad/pre-commit-snyk/blob/main/CONTRIBUTING.md)
      doc.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features).

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe):

Modified the IAC, Code & Test hooks to pass if a valid file is not found. 
Added the file extensions officially supported by Snyk.

## What is the current behavior

Currently, if a valid file is not found then the test fails which stops the commit. Ideally, this should pass as no vulnerability has been detected, the valid file is simply not present. 

Currently the only way around this is to remove the relevant test from the .pre-commit-config.yaml to pass.

## What is the new behavior

- Code / Test / IAC tests pass if valid file is not found.
- Hooks search for supported file extensions before scanning.
- Commit no longer fails if valid file is not present.

## Does this introduce a breaking change

- [ ] Yes
- [x] No

## Other information

---

Closes #{IssueNumber}

2024-04-06 03:55 UTC, fabasoad commented
Hey @Kieharper! Thank you for your contribution. I like the intention and the problem you're raising, but I don't like the way it is implemented. The problem with this implementation is that we try to list all the possible project types **supported by snyk** which should not be the concern of the pre-commit hook which is a wrapper in fact. This would lead to the situation when I will need to keep an eye on all supported and unsupported project types by snyk in a future and do a quick change (remove/add extension) in case snyk start supporting another project or stop supporting existing one.

What I can recommend is to change the implementation to achieve the same goal. Looking at the [snyk documentation](https://docs.snyk.io/snyk-cli/commands/test#exit-codes) snyk CLI exists with code `3` if no supported projects detected. You can use this information to exit with `0` in case snyk command exits with `3`. Something like:

```shell
snyk_exist_code=$(snyk test ...)
if [ $snyk_exist_code = 3 ]; then
  echo "No supported projects detected"
  exit 0
fi
exit "$snyk_exist_code"
```

LMKWYT.

2024-04-06 03:55 UTC, fabasoad requested changes
Left a comment above.

2024-04-08 11:10 UTC, Kieharper commented
Thanks @fabasoad, I hadn't thought to use the exit codes instead! I've modified the hooks to capture the exit codes and pass if either exit code 2 or 3 is given with the error. Whereas if exit code 1 is given then the hook fails as expected as vulnerabilities have been found.

2024-04-20 05:40 UTC, fabasoad requested changes
Hey! Thank you for the modifications you made after my last review. I've left a few comments. Please take a look. And sorry for the late reviews. I don't have too much free time recently.

2024-04-20 05:40 UTC, fabasoad commented on README.md
> +        args:["<folder>","--severity-threshold=<severity-level>"]
Please revert this change.

2024-04-20 05:40 UTC, fabasoad commented on hooks/snyk-code.sh
>  set -eu
```suggestion
set -u
```
Since you do `set +e` in the very next instruction. Same comment for other scripts.

2024-04-20 05:40 UTC, fabasoad commented on hooks/snyk-code.sh
> -bash "${SCRIPT_DIR}"/installation/main.sh
This script is needed to intall snyk if it does not exist locally. Is there any reason why you removed it?

2024-04-20 05:40 UTC, fabasoad commented on hooks/snyk-code.sh
> +snyk code test
```suggestion
snyk code test "$@"
```
We need to pass custom parameters defined by user (for example if user pass `-d` for debugging). Same comment for other scripts.

2024-04-20 05:40 UTC, fabasoad commented on hooks/snyk-code.sh
> +fi
```suggestion
```
I am not sure it is a good idea to pass hook if snyk exits with `2`. If it is code `2` then it means there was a problem with running snyk on this particular project (either problem with environment, or project, or anything else). The expectation of the user who configured `pre-commit-snyk` hook is to check vulnerabilities and likely block commit (or any other git event) if vulnerabilities are found. In this case project **still might have vulnerabilities** but environment might be misconfigured, and with this implementation we just silently allow to proceed which is not what is expected by user. I would leave it as is (fail the hook) and let user configure environment correctly.  Same comment for other scripts.

2024-04-20 05:40 UTC, fabasoad commented on hooks/snyk-code.sh
> +  echo "Valid files not found."
```suggestion
```
I think we can omit custom message since snyk itself prints clear message about it. Same comment for other scripts.

2024-04-20 05:40 UTC, fabasoad commented on .pre-commit-hooks.yaml
> +  pass_filenames: false
```suggestion
  pass_filenames: false
  verbose: true
```
Let's add `verbose: true` here as well for consistency. I do not have strong opinion about having `true` here by default at this moment. Let's give it a shot and will see.

2024-04-22 19:57 UTC, Kieharper reviewed
Recommended changes made, thank you for taking the time to review @fabasoad.

2024-05-01 14:25 UTC, fabasoad requested changes
Thank you for the changes. It looks great! There are 2 few minor things left and we're good to merge it.

2024-05-01 14:25 UTC, fabasoad commented on .pre-commit-hooks.yaml
> +  pass_filenames: false
```suggestion
```
Duplicate.

2024-05-01 14:25 UTC, fabasoad commented on hooks/snyk-test.sh
> +exit "$snyk_exit_code"
Do you mind to do similar changes in `hooks/snyk-log4shell.sh` for consistency?

2024-05-07 08:02 UTC, Kieharper reviewed
Suggested changes implemented, please review @fabasoad and thank you!

2024-05-15 14:32 UTC, fabasoad approved these changes
Thank you @Kieharper for the contribution! Everything looks good to me. I am merging the changes and will publish a new release right after that. P.S. CI is failing for scoop package manager but it seems it is not related to your PR. I will take a look at it separately.

2024-05-15 14:33 UTC, merged